# fly.toml app configuration file generated for backendtools on 2023-05-04T14:16:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backendtools"
primary_region = "scl"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
